# Generated by Django 4.0.4 on 2022-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_phn', models.BigIntegerField()),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_password', models.CharField(max_length=50)),
            ],
        ),
    ]
