# Generated by Django 4.0.4 on 2022-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='approved',
            field=models.CharField(default='not approved', max_length=100),
        ),
    ]
