# Generated by Django 4.1.2 on 2022-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_user_registration_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='approved',
            field=models.CharField(default='not approved', max_length=80),
        ),
    ]
